import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { SanityLive } from "@/sanity/lib/live";
import { poppins } from "@/utils/font";
import Footer from "@/components/Footer";
import WelcomePopup from "@/components/WelcomePopup";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body
          className={`${poppins.className} antialiased bg-[white] overflow-x-hidden`}
        >
          <Header/>
          <div className="h-[4rem]"></div>
          {children}
          {/* <QuickAddWrapper/> */}
          <Footer/>
          <SanityLive/>
          <WelcomePopup/>
        </body>
      </html>
    </ClerkProvider>
  );
}
