import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import {
  ClerkProvider
} from '@clerk/nextjs'
import { SanityLive } from "@/sanity/lib/live";
import { poppins } from "@/utils/font";
import Footer from "@/components/Footer";
import WelcomePopup from "@/components/WelcomePopup";
import { currentUser } from "@clerk/nextjs/server";
import { getAllFeaturedCategories } from "@/sanity/lib/categories/getAllFeaturedCategories";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const getUserAccessLevel = async () => {
  const user = await currentUser()
  return user?.publicMetadata?.accessLevel || 'public'
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const ALL_FEATURED_CATEGORY = await getAllFeaturedCategories();
  const user = await currentUser()
  const isPro = user?.publicMetadata?.type === "pro"

  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body
          className={`${poppins.className} antialiased bg-[#f7f2e9] overflow-x-hidden`}
        >
          <Header categories={ALL_FEATURED_CATEGORY} isPro={isPro}/>
          <div className="h-[4rem]"></div>
          {children}
          {/* <QuickAddWrapper/> */}
          <Footer/>
          <SanityLive/>
          <WelcomePopup/>
        </body>
      </html>
    </ClerkProvider>
  );
}
